sudo:
  - false

branches:
  only:
    - develop
    - stable

matrix:
  include:
    - name: "OS X / Xcode 10.3"
      os: osx
      osx_image: xcode10.3
      language: swift
      before_script:
        - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-osx-x86_64.zip
        - unzip protoc-3.6.1-osx-x86_64.zip
      script:
        - swift test

    - name: "OS X / Xcode 11.3"
      os: osx
      osx_image: xcode11.3
      language: swift
      before_script:
        - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-osx-x86_64.zip
        - unzip protoc-3.6.1-osx-x86_64.zip
      script:
        - swift test

    - name: "Ubuntu 16.04 / Swift 4.2.4"
      os: linux
      dist: xenial
      language: c
      before_script:
        - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
        - unzip protoc-3.6.1-linux-x86_64.zip
        - wget https://swift.org/builds/swift-4.2.4-release/ubuntu1604/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-ubuntu16.04.tar.gz
        - tar xzf swift-4.2.4-RELEASE-ubuntu16.04.tar.gz
        - export PATH=$(pwd)/swift-4.2.4-RELEASE-ubuntu16.04/usr/bin:"${PATH}"
        - swift --version
      script:
        - swift test

    - name: "Ubuntu 16.04 / Swift 5.1.3"
      os: linux
      dist: xenial
      language: c
      before_script:
        - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
        - unzip protoc-3.6.1-linux-x86_64.zip
        - wget https://swift.org/builds/swift-5.1.3-release/ubuntu1604/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-ubuntu16.04.tar.gz
        - tar xzf swift-5.1.3-RELEASE-ubuntu16.04.tar.gz
        - export PATH=$(pwd)/swift-5.1.3-RELEASE-ubuntu16.04/usr/bin:"${PATH}"
        - swift --version
      script:
        - swift test

    - name: "Ubuntu 16.04 / Swift latest"
      os: linux
      dist: xenial
      language: c
      before_script:
        - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
        - unzip protoc-3.6.1-linux-x86_64.zip
        - wget "https://swift.org/builds/development/ubuntu1604/swift-DEVELOPMENT-SNAPSHOT-2020-01-04-a/swift-DEVELOPMENT-SNAPSHOT-2020-01-04-a-ubuntu16.04.tar.gz"
        - tar xzf swift-DEVELOPMENT-SNAPSHOT-2020-01-04-a-ubuntu16.04.tar.gz
        - export PATH=$(pwd)/swift-DEVELOPMENT-SNAPSHOT-2020-01-04-a-ubuntu16.04/usr/bin:"${PATH}"
        - swift --version
      script:
        - swift test
